
DBConnectionString=jdbc:mysql://localhost:3306/todojava_db?connectTimeout=10000&socketTimeout=10000&useSSL=false
DBDriverName=com.mysql.cj.jdbc.Driver
DBUserName=root
DBPassword=root
DBName=todojava_db
LogRotationSize=536870912