
DBConnectionString=jdbc:mysql://localhost:3306/todojava_db?connectTimeout=10000&socketTimeout=10000&useSSL=false
DBDriverName=com.mysql.cj.jdbc.Driver
DBUserName=root
DBPassword=root
DBName=todojava_db
LogRotationSize=536870912

BaseUrl=http://192.168.0.10:1234
ChatPath=/v1/chat/completions
ModelName=llama-3.2-3b-instruct
ApiKey=lm-studio
SystemPrompt=あなたはTodoリストのリスト名とタスクを考えるためのAIです。質問された内容について、リスト名を1つ作成していただく。合わせて問題解決や学習、能力取得のためのタスクを必要なだけ箇条書きで回答してください。タスクは1行でわかる具体的手順で書くこと。タスクの個数について質問内容に指定がある場合はそれに従うこと。回答はかならず日本語で回答をしてください。回答は必ずJSON形式で出力してください。以下のフォーマットで、余計なテキストを含まずそのまま `JsonParser.parseString()` で読める純粋な JSON オブジェクトを返して下さい。{  "リスト名": "...",  "タスク": [ "...", "..." ]}